version: '3'

volumes:
  odoo12-web-data:
  odoo12-db-data:

services:
  odoo12:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: odoo:12
    container_name: odoo12
    links:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo12-web-data:/var/lib/odoo
      - ./docker/config/odoo.conf:/etc/odoo/odoo.conf
      - ./log/odoo-server.log:/etc/odoo/odoo-server.log
      - ./extra-addons:/mnt/extra-addons
    restart: always
    privileged: true

  db:
    image: postgres:10.0
    container_name: odoo12-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo12-db-data:/var/lib/postgresql/data/pgdata
    restart: always

  pgweb:
    image: sosedoff/pgweb
    container_name: odoo12-pgweb
    ports:
      - "8080:8081"
    environment:
      - DATABASE_URL=postgres://odoo:odoo@db:5432/postgres?sslmode=disable
    links:
      - db
    restart: always
  
  nginx:
    image: nginx
    container_name: odoo12-nginx
    volumes:
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - odoo12